apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }} 
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # The port you want to expose within the cluster
      targetPort: {{ .Values.service.targetPort }} # The port your application listens on within the pod
  type: {{ .Values.service.type }} # Change to 'LoadBalancer' or 'NodePort' if you need external access
