apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidetube-studio
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: sidetube-studio
  template:
    metadata:
      labels:
        app: sidetube-studio
    spec:
      containers:
        - name: sidetube-studio-container
          image: sidetube-registry:52271/sidetube-studio:latest
          ports:
            - containerPort: 80 # The port your application listens on
          env:
            # net setting
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_secret_key
            - name: JWT_HEADER_ALG
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_header_alg
            - name: HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: sidetube-studio-configmap
                  key: http_address
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-studio-configmap
                  key: http_port
            #mongo
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sidetube-mongo-secret
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sidetube-mongo-secret
                  key: mongodb_password
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongodb_host
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongo_database
            - name: MONGO_VIDEO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongo_video_collection
            #rabbitmq
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: RABBIT_HOST
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: RABBIT_PORT
            - name: RABBIT_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: sidetube-rabbitmq-secret
                  key: RABBIT_USER_NAME
            - name: RABBIT_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: sidetube-rabbitmq-secret
                  key: RABBIT_USER_PASS
            - name: INSERT_SEARCH_ENGINE_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: INSERT_SEARCH_ENGINE_EXCHANGE
            - name: INSERT_SEARCH_ENGINE_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: INSERT_SEARCH_ENGINE_QUEUE
            # others
            - name: CROS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: cros_allow_origin
            - name: VIDEO_PATH
              valueFrom:
                configMapKeyRef:
                  name: sidetube-video-configmap
                  key: video_path
            - name: DEVELOPMENT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: development
          volumeMounts:
            - name: videos-data
              mountPath: /var/videos/
      volumes:
        - name: videos-data
          persistentVolumeClaim:
            claimName: videos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sidetube-studio-service
spec:
  selector:
    app: sidetube-studio
  ports:
    - protocol: TCP
      port: 80 # The port you want to expose within the cluster
      targetPort: 80 # The port your application listens on within the pod
  type: LoadBalancer # Change to 'LoadBalancer' or 'NodePort' if you need external access
