version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: user
    restart: always
    networks:
      - network_mongo
    volumes:
      - ../../../tempVideo/:/var/videos/
    ports:
      - "3007:80"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=80
      - GRPC_ADDRESS=172.17.0.1
      - GRPC_PORT=3006
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=mongodb://172.17.0.1:27017/
      - MONGO_DATABASE=video_meta
      - MONGO_USER_COLLECTION=user
      - MONGO_VIDEO_COLLECTION=videoMeta
      - MONGO_HISTORY_COLLECTION=viewLogs
      - JWT_ACCESS_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_HEADER_ALG=HS256
      - CROS_ALLOW_ORIGIN=http://localhost:3000	
      - DEVELOPMENT=test

networks:
  network_mongo:
    name: mongo_default
    external: true
