apiVersion: v1
kind: Secret
metadata:
  name: sidetube-secret
type: Opaque
stringData:
  jwt_access_secret_key: G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
  jwt_secret_key: G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
  jwt_header_alg: HS256
  jwt_access_header_alg: HS256
