// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package JwtGererater

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JwtTokenClient is the client API for JwtToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JwtTokenClient interface {
	RefreshToken(ctx context.Context, in *Requset, opts ...grpc.CallOption) (*Respond, error)
}

type jwtTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtTokenClient(cc grpc.ClientConnInterface) JwtTokenClient {
	return &jwtTokenClient{cc}
}

func (c *jwtTokenClient) RefreshToken(ctx context.Context, in *Requset, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/JwtToken.JwtToken/refreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtTokenServer is the server API for JwtToken service.
// All implementations must embed UnimplementedJwtTokenServer
// for forward compatibility
type JwtTokenServer interface {
	RefreshToken(context.Context, *Requset) (*Respond, error)
	mustEmbedUnimplementedJwtTokenServer()
}

// UnimplementedJwtTokenServer must be embedded to have forward compatible implementations.
type UnimplementedJwtTokenServer struct {
}

func (UnimplementedJwtTokenServer) RefreshToken(context.Context, *Requset) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedJwtTokenServer) mustEmbedUnimplementedJwtTokenServer() {}

// UnsafeJwtTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwtTokenServer will
// result in compilation errors.
type UnsafeJwtTokenServer interface {
	mustEmbedUnimplementedJwtTokenServer()
}

func RegisterJwtTokenServer(s grpc.ServiceRegistrar, srv JwtTokenServer) {
	s.RegisterService(&JwtToken_ServiceDesc, srv)
}

func _JwtToken_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Requset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtTokenServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JwtToken.JwtToken/refreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtTokenServer).RefreshToken(ctx, req.(*Requset))
	}
	return interceptor(ctx, in, info, handler)
}

// JwtToken_ServiceDesc is the grpc.ServiceDesc for JwtToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JwtToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JwtToken.JwtToken",
	HandlerType: (*JwtTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "refreshToken",
			Handler:    _JwtToken_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token.proto",
}
