apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidetube-generate-mpd
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: sidetube-generate-mpd
  template:
    metadata:
      labels:
        app: sidetube-generate-mpd
    spec:
      containers:
        - name: sidetube-generate-mpd-container
          image: sidetube-registry:52271/sidetube-generate-mpd:latest
          env:
            #rabbitmq
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: RABBIT_HOST
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: RABBIT_PORT
            - name: RABBIT_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: sidetube-rabbitmq-secret
                  key: RABBIT_USER_NAME
            - name: RABBIT_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: sidetube-rabbitmq-secret
                  key: RABBIT_USER_PASS
            - name: INSERT_SEARCH_ENGINE_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: INSERT_SEARCH_ENGINE_EXCHANGE
            - name: INSERT_SEARCH_ENGINE_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: INSERT_SEARCH_ENGINE_QUEUE
            - name: GENERATE_MPD_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: GENERATE_MPD_QUEUE
            - name: GENERATE_MPD_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-rabbitmq-configmap
                  key: GENERATE_MPD_EXCHANGE
            # redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: sidetube-redis-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-redis-configmap
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: sidetube-redis-configmap
                  key: REDIS_DB
              #mongo
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sidetube-mongo-secret
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sidetube-mongo-secret
                  key: mongodb_password
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongodb_host
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongo_database
            - name: MONGO_VIDEO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: sidetube-mongo-configmap
                  key: mongo_video_collection
            # others
            - name: NUMBER_OF_WORKER
              valueFrom:
                configMapKeyRef:
                  name: sidetube-generate-mpd-configmap
                  key: NUMBER_OF_WORKER
            - name: VIDEO_PATH
              valueFrom:
                configMapKeyRef:
                  name: sidetube-video-configmap
                  key: video_path
            - name: DEVELOPMENT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: development
          volumeMounts:
            - name: videos-data
              mountPath: /var/videos/
      volumes:
        - name: videos-data
          persistentVolumeClaim:
            claimName: videos-pvc
