version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jwtGenerate
    restart: always
    networks:
      - network_mongo
    volumes:
      - ../../../tempVideo/:/var/videos/
    ports:
      - "3005:80"
      - "3006:81"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - GRPC_ADDRESS=0.0.0.0
      - HTTP_PORT=80
      - GRPC_PORT=81
      - JWT_ACCESS_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_HEADER_ALG=HS256
      - JWT_ACCESS_HEADER_ALG=HS256
      - CROS_ALLOW_ORIGIN=http://localhost:3000
      - DEVELOPMENT=test

networks:
  network_mongo:
    name: mongo_default
    external: true
