version : '3'
services:
  search:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: search
    restart: always
    networks: 
     - network_mongo
     - network_elastic
    ports:
      - "3010:80"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=80
      - ELASTIC_HOST=172.17.0.1
      - ELASTIC_PORT=9200
      - ELASTIC_INDEX=videos
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=mongodb://mongo:27017/
      - MONGO_DATABASE=video_meta
      - MONGO_VIDEO_COLLECTION=videoMeta
      - JWT_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_HEADER_ALG=HS256
      - CROS_ALLOW_ORIGIN=http://localhost:3000
networks:
  network_mongo:
    name: mongo_default
    external: true
  network_elastic:
    name: elastic
    external: true
    driver: bridge



