apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidetube-token
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: sidetube-token
  template:
    metadata:
      labels:
        app: sidetube-token
    spec:
      containers:
        - name: sidetube-token-container
          image: sidetube-registry:52271/sidetube-token:latest
          ports:
            - containerPort: 80 # The port your application listens on
            - containerPort: 81 # The port your application listens on
          env:
            - name: JWT_ACCESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_access_secret_key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_secret_key
            - name: JWT_HEADER_ALG
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_header_alg
            - name: JWT_ACCESS_HEADER_ALG
              valueFrom:
                secretKeyRef:
                  name: sidetube-secret
                  key: jwt_access_header_alg
            - name: HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: http_address
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: http_port
            - name: GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: grpc_address
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: grpc_port
            - name: CROS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: cros_allow_origin
            - name: DEVELOPMENT
              valueFrom:
                configMapKeyRef:
                  name: sidetube-configmap
                  key: development
---
apiVersion: v1
kind: Service
metadata:
  name: sidetube-token-service
spec:
  selector:
    app: sidetube-token
  ports:
    - name: http
      protocol: TCP
      port: 80 # The port you want to expose within the cluster
      targetPort: 80 # The port your application listens on within the pod
    - name: grpc
      protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer # Change to 'LoadBalancer' or 'NodePort' if you need external access
