version : '3'
services:
  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: encodeVideo
    restart: always
    networks: 
     - network_mongo
    volumes:
    - ../../../../tempVideo/:/var/videos/
    environment:
      - VIDEO_PATH=/var/videos/
      - RABBIT_USER_NAME=guest
      - RABBIT_USER_PASS=guest
      - RABBIT_HOST=172.17.0.1
      - RABBIT_PORT=5672
      - ENCODE_VIDEO_EXCHANGE=encode_video_exchange
      - ENCODE_VIDEO_QUEUE=encode_video
      - GENERATE_MPD_EXCHANGE=generate_mpd_exchange
      - GENERATE_MPD_QUEUE=generate_mpd
      - REDIS_HOST=172.17.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - NUMBER_OF_WORKER=1

networks:
  network_mongo:
    name: mongo_default
    external: true



