version : '3'
services:
  videostreaming:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: VideoStreaming
    restart: always
    networks: 
     - network_mongo
    volumes:
    - ../../../tempVideo/:/var/videos/
    ports:
      - "3003:80"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=80
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=172.17.0.1:27017/
      - MONGO_DATABASE=video_meta
      - MONGO_VIDEO_COLLECTION=videoMeta
      - MONGO_VIEW_LOGS_COLLECTION=viewLogs
      - JWT_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_HEADER_ALG=HS256
      - CROS_ALLOW_ORIGIN=http://localhost:3000
      - VIDEO_PATH=/var/videos/

networks:
  network_mongo:
    name: mongo_default
    external: true



