version : '3'
services:
  channelstudio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: channelstudio
    restart: always
    networks: 
     - network_mongo
    # volumes:
    # - ../../../tempVideo/:/var/videos/
    ports:
      - "3002:80"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=80
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=mongodb://172.17.0.1:27017/
      - MONGO_DATABASE=video_meta
      - MONGO_COLLECTION=videoMeta
      - JWT_SECRET_KEY=G3yd6JluDc7ZtaTC2opHra!5ZMSay9IO1faUuBW0
      - JWT_HEADER_ALG=HS256
      - CROS_ALLOW_ORIGIN=http://127.0.0.1:3000

networks:
  network_mongo:
    name: mongo_default
    external: true



